GENERIC_ERROR_MESSAGE = "Sorry. An error occurred. Please try again."
INVALID_LOGIN = "Sorry. We couldn't log you in. Please check your username and password and try again."
DUPLICATE_EMAIL = "Sorry. That username is already registered."
LOBBY_ROOM_NAME = "LOBBY"
GAME_ROOM_PREFIX = "GAME_ROOM_NO_"
